# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/greeting.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/greeting.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15protos/greeting.proto\"-\n\x0b\x43lientInput\x12\x10\n\x08greeting\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1f\n\x0cServerOutput\x12\x0f\n\x07message\x18\x01 \x01(\t21\n\x07Greeter\x12&\n\x05greet\x12\x0c.ClientInput\x1a\r.ServerOutput\"\x00\x62\x06proto3'
)




_CLIENTINPUT = _descriptor.Descriptor(
  name='ClientInput',
  full_name='ClientInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='greeting', full_name='ClientInput.greeting', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='ClientInput.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=70,
)


_SERVEROUTPUT = _descriptor.Descriptor(
  name='ServerOutput',
  full_name='ServerOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='ServerOutput.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=103,
)

DESCRIPTOR.message_types_by_name['ClientInput'] = _CLIENTINPUT
DESCRIPTOR.message_types_by_name['ServerOutput'] = _SERVEROUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientInput = _reflection.GeneratedProtocolMessageType('ClientInput', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTINPUT,
  '__module__' : 'protos.greeting_pb2'
  # @@protoc_insertion_point(class_scope:ClientInput)
  })
_sym_db.RegisterMessage(ClientInput)

ServerOutput = _reflection.GeneratedProtocolMessageType('ServerOutput', (_message.Message,), {
  'DESCRIPTOR' : _SERVEROUTPUT,
  '__module__' : 'protos.greeting_pb2'
  # @@protoc_insertion_point(class_scope:ServerOutput)
  })
_sym_db.RegisterMessage(ServerOutput)



_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=105,
  serialized_end=154,
  methods=[
  _descriptor.MethodDescriptor(
    name='greet',
    full_name='Greeter.greet',
    index=0,
    containing_service=None,
    input_type=_CLIENTINPUT,
    output_type=_SERVEROUTPUT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
